DROP TABLE IF EXISTS books;

DROP TABLE IF EXISTS customers;

DROP TABLE IF EXISTS roles;

CREATE TABLE books (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(40), author VARCHAR(50), subject VARCHAR(30), price DOUBLE);

CREATE TABLE customers(id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(30), password VARCHAR(100), mobile VARCHAR(15), address VARCHAR(60), email VARCHAR(40) UNIQUE, birth DATE, enabled INT);

CREATE TABLE roles(email VARCHAR(50), role VARCHAR(30));
